Feature/alb augmix
aiorhiroki/farmer pull request #131
Opened 2020-09-15 05:02 UTC by sirn524

## 実施したこと

* Albumentationsにaug_mixの分岐を実装
* segmentations_aug.pyのリファクタリングと一部Kerasモジュールの削除
* yaml上でAugmentationの実行する種類を選べるようになる（と言っても選択肢は今の所Albumentationsのみ）

## やらないこと

* Keras(ImageDataGenerator)によるAugmentation分岐の実装
* Albumentations以外のAugmentationModuleの実装

## できるようになること（ユーザ目線）

* Augmixによる複雑なaugmentation
* より多くのAugmentationモジュールの受け入れ準備
* yamlにてaugmix : yesでaugmixへの分岐を実行できるようになった

## できなくなること（ユーザ目線）

* yamlのaugmentation_statを明記しないと、augmentationが実行されないようになった

## 動作確認

* DL2にてexampleでの動作確認
* GitHub Actionsでの動作確認

## その他

* yamlからの操作が少し複雑になりました。augmentation_stat, augmixの入力が必要になります。
* augmixモジュールの導入による実行効果の実験はしていません。精度が下がる場合にはaugmix: no(false)をdefault, exampleにも反映します。

2020-09-17 04:54 UTC, sirn524 commented
Conflictの解消後、train_paramsのfeatureがマージされたため、train_paramsにaugmix parameter2つを追加
追加要項
・augmentation_stat --- augmentationの種類が増えるに連れて、yamlでの操作が可能となる
・augmix --- true, falseでmixをするかどうかを決定する。

2020-09-17 04:57 UTC, sirn524 commented
train paramsのパラメータ追加が良かったのかどうかは応相談と思われる。
augmix true-- booleanはいるべきか？まぁ、cosine_decayもbool値あるしOK？

2020-09-18 01:51 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +            label = label
augmixがTrue or Flaseさえあれば十分だと思ったけど、
`aug_stat`が必要な理由って何？

2020-09-18 01:51 UTC, aiorhiroki commented on farmer/domain/model/train_params_model.py
> +
最終行

2020-09-18 01:51 UTC, aiorhiroki commented on farmer/domain/model/train_params_model.py
> +
最終行がないよ

2020-09-18 01:51 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +def segmentation_alb(
関数名は`segmentation_aug`の方がよさそう
alb以外も使う統合された関数になったから。

2020-09-18 01:54 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +            label = label
山田さんが起票した、オリジナルのaugmixにkeras ImageDataGeneratorの分岐があったので、そこの追加がしたくて作りました。(スコープからは外れていましたので、Generator自体の実装はしていないですが）このfeatureだと必要ないということであれば、消してもいいかもです

2020-09-18 01:54 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +def segmentation_alb(
そうですね、augに書き換えします！

2020-09-18 02:05 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +            label = label
このfeatureでは一旦消して良さそう。また追加された時に復活する感じで。

あと、`label = label`はいらない 👼

2020-09-18 02:07 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +            augmented = augment_and_mix(augmented[image], mean, std,)
**std,)** 最後にごみある

2020-09-18 02:28 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +            label = label
了解です

2020-09-18 02:43 UTC, yumion commented
> 山田さんが起票した、オリジナルのaugmixにkeras ImageDataGeneratorの分岐があったので、そこの追加がしたくて作りました。

これ、ImageDataGeneratorを使っていたときにAugMixを入れただけなので、ImageDataGeneratorは必要ないですよ。
あと、 `augment_and_mix` は入力画像だけにしかaugmentationをしないので、labelもaugmentationした方を使っていただけると嬉しいです（そっちはalbumentationsで実装もしてますし）

2020-09-18 02:57 UTC, sirn524 commented
まず松崎さんからいただいた指摘部分反映後、label(mask)をaugmixするように組み込みを分解して考えることにします。
ImageDataGeneratorで目新しいAugmentationとかないですかね。。。random erasingとかも組み込みたいので、別featureで追加（ImageDataGenerator以外でも）検討します

2020-09-18 03:01 UTC, yumion commented
> ImageDataGeneratorで目新しいAugmentationとかないですかね

ないと思います…

2020-09-18 03:57 UTC, sirn524 commented
指摘いただいたパートはresolveしましたー

2020-09-18 04:52 UTC, sirn524 commented
label,maskの両方がaugment and mixに入るようにしてみた

2020-09-18 05:40 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> -    if len(transforms) > 0:
`if len(transforms) > 0:`
これなくて良いの？

2020-09-18 05:56 UTC, yumion commented on farmer/ncc/augmentation/segmentation_aug.py
> +        augmented['mask'] = augment_and_mix(augmented['mask'], mean, std)
これ、imageとmask一致しないですよ
ランダムにaugmentation選ぶので、別で実行すると別のaugmentationがmixされます

2020-09-18 05:57 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> -    if len(transforms) > 0:
消しちゃってました、、、絶対必要です

2020-09-18 05:59 UTC, yumion commented on farmer/ncc/augmentation/segmentation_aug.py
> +        augmented['mask'] = augment_and_mix(augmented['mask'], mean, std)
ここを参考にしてください
https://github.com/Project-zero-one/Hypogastric_nerve/blob/b5ed957e70ba65f91273d9101c3212f0048f1fbc/src/augmentations.py#L217

2020-09-18 09:23 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> -
この3行も消しちゃまずそう

2020-09-25 00:59 UTC, aiorhiroki requested changes
classificationの対応と、yamlのtransformsを使うaugmixをすること。

2020-09-25 00:59 UTC, aiorhiroki commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
segmentationにしか、augmixできなくなるけど、classificationでもやるよね。
元々のaugment_and_mix消す必要ないと思う。

2020-09-25 00:59 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +        label, mean,
ここ改行しよう

2020-09-25 00:59 UTC, aiorhiroki commented on farmer/ncc/augmentation/segmentation_aug.py
> +                mean, std
このdual_augment_and_mixにyamlで指定したtransformsを入れるんじゃないの？

2020-09-25 00:59 UTC, aiorhiroki commented on example/yamls/segmentation.yaml
> +    augmix: yes
できるなら、augmentationの中に、augmixがあった方が見え方が綺麗だよね。
難しいかな？

2020-09-25 01:23 UTC, sirn524 commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
改行の関係でaugment_and_mixが下に行っているため、消したように見えているだけっぽいです。
ファイル変更なしでresolveしてもよろしいですか？

2020-09-25 01:23 UTC, sirn524 commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
見え方悪いですが、オリジナルのaugment_and_mixは残っています。行数の関係で場所を入れ替えたので消えたように記述されているのかと思います。

2020-09-25 01:23 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +        label, mean,
承知しました、確かに文字数ではなく要素で言ったら独立ですね、、、失礼しました

2020-09-25 01:27 UTC, aiorhiroki commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
あ、ほんとだね
ClassificationDatasetにaugmentationのコード書いて欲しいなー

2020-09-25 01:29 UTC, sirn524 commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
わかりました、やってみます

2020-09-25 01:33 UTC, aiorhiroki commented on example/yamls/segmentation.yaml
> +    augmix: yes
パッと見、難しそうだね。このままでいいか

2020-10-06 05:11 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +        augmented['mask'] = augment_and_mix(augmented['mask'], mean, std)
dual_augmentの変更により解消済み

2020-10-06 05:27 UTC, sirn524 commented on farmer/ncc/augmentation/segmentation_aug.py
> +                mean, std
transforms抜けてました。なぜ気づかなかったか不思議なくらいです。すみません

2020-10-06 05:27 UTC, sirn524 commented on farmer/ncc/augmentation/augment_and_mix.py
> +    """Perform AugMix augmentations and compute mixture.
classification 側はaugment_and_mixのみで対応するように書き換えました。

2020-10-22 05:56 UTC, aiorhiroki requested changes
segmentation_aug.pyの中にclassification_augを書くのは違うから、
classification_aug.pyを作るか、albumentation_aug.pyで二つをまとめるか、どちらかが必要

2020-10-22 05:56 UTC, aiorhiroki commented on farmer/ncc/generators/dataset.py
> +            input_image, label = classification_aug(
classification_augが定義されてないよ

2020-10-30 01:31 UTC, aiorhiroki reviewed
コンフリクト解消もお願いします...

2020-10-30 01:31 UTC, aiorhiroki commented on farmer/ncc/augmentation/classification_aug.py
> +        augmented = aug(image=input_image, mask=label)
classificationの時は、mask,labelどちらも必要ないね

2020-10-30 01:31 UTC, aiorhiroki commented on farmer/ncc/augmentation/classification_aug.py
> +def get_aug(augmentation_dict):
同じ関数が出てきてるのは美しくないから、ここは共通化しておきたいな。
utils.pyとか作れば良さそう

2020-11-26 08:37 UTC, sirn524 commented
一旦conflictのresolveとclassificationのいらないパートを消す等のreviewいただいたパートは全部修正しました。
Classificationの挙動についてもう少し調べたいので、review指摘頂きつつでも良いですか？

2020-12-01 06:03 UTC, aiorhiroki reviewed
差分が多くなってしまっているけど、たぶん良さそう！

2020-12-01 06:03 UTC, aiorhiroki commented on farmer/ncc/augmentation/augment_and_mix.py
> +    image_mix = np.zeros_like(image)
これ`mix`を`image_mix`に変えて問題ない？

2020-12-01 06:19 UTC, sirn524 commented on farmer/ncc/augmentation/augment_and_mix.py
> +    image_mix = np.zeros_like(image)
def augment_and_mixは、classificationしか使わないので、影響はないと思います。
for文の中のmix が変わってなかったので一部修正します。

2020-12-15 00:57 UTC, merged