Feature/mlflow
aiorhiroki/farmer pull request #179
Opened 2021-09-03 02:53 UTC by yHarai

- mlflowのAPIを提供するラッパークラスを作成
- yamlのオプション追加によるtrainer_modelの変更
- 結果出力の際にmlrunsディレクトリにも結果を残すようにする

2021-09-15 09:58 UTC, aiorhiroki requested changes
基本的にわかりやすくて良いです！
あとは、NCC固有のコードを設定yamlで外に出してもらえると！

2021-09-15 09:58 UTC, aiorhiroki commented on farmer/domain/model/trainer_model.py
> +                'Hypogastric': '/mnt/cloudy_z/input/Hypogastric_nerve/train_test.dvc'
NCC固有のパスなどは入れない方針で行きたいです。
設定yamlの引数などに入れれますか？

2021-09-15 09:58 UTC, aiorhiroki commented on farmer/ncc/mlflow_wrapper/mlflow_client_wrapper.py
> +    TRACKING_URI = '/mnt/cloudy_z/result/mlruns'
ここも、NCC固有のコードにしない方法が良いです

2021-09-15 23:42 UTC, yHarai commented on farmer/domain/model/trainer_model.py
> +                'Hypogastric': '/mnt/cloudy_z/input/Hypogastric_nerve/train_test.dvc'
ご指摘ありがとうございます。修正します。

2021-09-16 04:38 UTC, Yuto-web reviewed
僕の方は特に指摘はありません。
大丈夫です！

2021-09-16 06:50 UTC, yHarai commented on farmer/domain/model/trainer_model.py
> +                'Hypogastric': '/mnt/cloudy_z/input/Hypogastric_nerve/train_test.dvc'
@aiorhiroki 修正いたしました。ご確認お願いいたします。

https://github.com/aiorhiroki/farmer/pull/179/commits/aa783e4f3f84977c2e29366298e2c7ac78e3b914

2021-10-08 08:58 UTC, aiorhiroki reviewed
yamlに具体的な名前が入る場合は、個別のリポジトリでyaml管理をするのが良いかもしれません。。

2021-10-08 08:58 UTC, aiorhiroki commented on example/yamls/segmentation.yaml
> +    'Ureter': '/mnt/cloudy_z/input/Ureter/train_test.dvc'
気づくの遅くなりましたが、ここもダメですね。。

2021-10-10 23:55 UTC, yHarai commented on example/yamls/segmentation.yaml
> +    'data_name': './data.dvc' # path to dvc
@aiorhiroki パス記載部を修正しました。

2021-10-10 23:55 UTC, yHarai commented on example/yamls/segmentation.yaml
> +    'Ureter': '/mnt/cloudy_z/input/Ureter/train_test.dvc'
修正しましたのでご確認をお願いいたします。

2021-10-14 07:56 UTC, merged